# basic settings
title: "Julia CV Resume & Personal Portfolio"
email: "hello@julianowe.de"
description: "I am UX Designer and psychologist. My emphasis in design is minimalism, empathy and openess to creativity."
author: "Julia"
domain: julianowe.de
baseurl: "" 
url: https://julianowe.de # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%d %B %Y"

# paginations & permalinks
paginate: 6
paginate_path: "/blog/page:num/"
permalink: pretty

# disqus comments
disqus_comments: "no" # yes - show disqus comments, no - hide disqus comments
disqus_shortname: "" # read more here https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# formsubmit.io
formspree_endpoint: "https://formspree.io/f/mgvwweqz" # sign up on https://formspree.io/ and create your form endpoint

# Google Tag Manager
google_tag_manager: GTM-TR545KC6

#Recaptcha
recaptcha_site_key: #6LfKb_8pAAAAAE2dV4gdWq6UDwylF2Qx3Ja983Qu

# collections
collections:
  works:
    output: true
    permalink: /:collection/:name
defaults:
  - scope:
      path: "works/"
    values:
      layout: "works-single"


# archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Build settings
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _config.dev.yml

sass:
  style: compressed

markdown: kramdown
