# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/preloader-image.png"
    alt: "Loading..."

### Header
header:
  logo:
    image: "assets/img/Home-light-Icon.png"
    alt: "Julia Nowe"
    width: 28
    height: 24

### Social
social:
  - title: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/julia-nowe-82a2b8222/"


### Footer
footer:
  developer: "Created in <strong>Jekyll & Github</strong>"
  copyright: "Copyright &copy; <strong>Julia Nowe</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "Bootcamp"
      slug: "bootcamp"

    - name: "Commercial"
      slug: "commercial"
