# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "Julia Nowe"

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: "Julia Nowe"

### Social
social:
  - title: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "http://linkedin.com"


### Footer
footer:
  developer: "Created in <strong>Jekyll & Github</strong>"
  copyright: "Copyright &copy; <strong>Julia Nowe</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "Bootcamp"
      slug: "ui-ux-design"

    - name: "Commercial"
      slug: "photography"
